import { join } from "node:path";
import { createCheckCollector } from "./factory-doctor.mjs";
import { assertRemoteAuthorized } from "./remote-guard.mjs";

const noop = () => {};

export function serviceUrl(service) {
  return service?.status?.url || null;
}

export function serviceIapEnabled(service) {
  return String({ ...(service?.metadata?.annotations || {}) }["run.googleapis.com/iap-enabled"] || "").toLowerCase() === "true";
}

export function serviceMemory(service) {
  try { return service.spec.template.spec.containers[0].resources.limits.memory; } catch { return null; }
}

export function serviceEnv(service, key) {
  try { return (service.spec.template.spec.containers[0].env || []).find((item) => item.name === key)?.value; } catch { return undefined; }
}

export function terraformVarArgs(cfg, extra = {}) {
  const vars = {
    project_id: cfg.project,
    project_number: cfg.projectNumber,
    agent_identity_org_id: cfg.agentIdentityOrgId,
    gemini_enterprise_app_id: cfg.geAppId,
    region: cfg.region,
    gemini_enterprise_location: cfg.geLocation,
    ...extra,
  };
  const args = [];
  for (const [key, value] of Object.entries(vars)) {
    if (value !== undefined && value !== "" && value !== null) args.push("-var", `${key}=${value}`);
  }
  return args;
}

function parseBindings(text) {
  try {
    return JSON.parse(text || "{}").bindings || [];
  } catch {
    return [];
  }
}

export function createFactoryPlane({
  repoRoot,
  terraformDir,
  ensureGcloud,
  ensureTerraform,
  ensureAgentIdentityConfig,
  persistAgentIdentityConfig,
  tfOutputs,
  run,
  gcloud,
  gitShortSha,
  writeTextFile,
  authorize = assertRemoteAuthorized,
} = {}) {
  if (!repoRoot || !terraformDir || !ensureGcloud || !ensureTerraform || !ensureAgentIdentityConfig || !persistAgentIdentityConfig || !tfOutputs || !run || !gcloud || !gitShortSha || !writeTextFile) {
    throw new Error("createFactoryPlane requires repo, terraform, identity, command, and file dependencies");
  }

  function describeRun(cfg, service) {
    const result = gcloud(["run", "services", "describe", service, "--project", cfg.project, "--region", cfg.region, "--format=json"], { allowFail: true });
    if (!result.ok) return null;
    try { return JSON.parse(result.out); } catch { return null; }
  }

  function resolveRepo(cfg) {
    const outputs = tfOutputs();
    return outputs.artifact_repository || `${cfg.region}-docker.pkg.dev/${cfg.project}/ge-agent-factory`;
  }

  function builderImageTag(cfg) {
    return `${resolveRepo(cfg)}/ge-agent-factory-builder:latest`;
  }

  function infra(cfg, { sub, gatewayImage, workerImage, yes = false, log = noop } = {}) {
    ensureTerraform();
    const chdir = `-chdir=${terraformDir}`;
    const imageVars = {};
    if (gatewayImage) imageVars.gateway_image = gatewayImage;
    if (workerImage) imageVars.worker_image = workerImage;
    if (["apply", "plan"].includes(sub)) {
      if (!cfg.project || !cfg.projectNumber) throw new Error("project & projectNumber required (run `ge init`).");
      if (!cfg.geAppId) throw new Error("geAppId required.");
      ensureAgentIdentityConfig(cfg, { log });
      persistAgentIdentityConfig(cfg);
      const lines = [
        "# Generated by `ge infra` from .ge.json / env.",
        `project_id                 = "${cfg.project}"`,
        `project_number             = "${cfg.projectNumber || ""}"`,
        `agent_identity_org_id      = "${cfg.agentIdentityOrgId || ""}"`,
        `region                     = "${cfg.region}"`,
        `gemini_enterprise_app_id   = "${cfg.geAppId || ""}"`,
        `gemini_enterprise_location = "${cfg.geLocation}"`,
      ];
      writeTextFile(join(repoRoot, "installer", "values.tfvars"), lines.join("\n") + "\n");
      log("wrote installer/values.tfvars");
    }
    switch (sub) {
      case "init":
        run("terraform", [chdir, "init"], { capture: false });
        return { sub };
      case "plan":
        run("terraform", [chdir, "init", "-input=false"], { capture: false });
        run("terraform", [chdir, "plan", ...terraformVarArgs(cfg, imageVars)], { capture: false });
        return { sub };
      case "apply":
        run("terraform", [chdir, "init", "-input=false"], { capture: false });
        run("terraform", ["-chdir=" + terraformDir, "apply", "-auto-approve", ...terraformVarArgs(cfg, imageVars)], { capture: false });
        return { sub };
      case "output":
        return { sub, outputs: tfOutputs() };
      case "destroy":
        if (!yes) throw new Error("refusing to destroy without yes=true");
        run("terraform", [chdir, "destroy", "-auto-approve", ...terraformVarArgs(cfg)], { capture: false });
        return { sub };
      default:
        throw new Error("usage: ge infra <init|plan|apply|output|destroy>");
    }
  }

  function build(cfg, { target, log = noop } = {}) {
    ensureGcloud();
    if (!cfg.project) throw new Error("No project. Run `ge init`.");
    if (target === "builder") {
      const repo = resolveRepo(cfg);
      run("gcloud", ["artifacts", "repositories", "create", repo.split("/").pop(), "--repository-format=docker", "--location", cfg.region, "--project", cfg.project], { allowFail: true });
      const image = builderImageTag(cfg);
      log(`building shared builder image → ${image}`);
      run("gcloud", ["builds", "submit", "apps/ge-demo-generator", "--project", cfg.project, "--config", "apps/ge-demo-generator/cloudbuild.builder.yaml", "--substitutions", `_IMAGE=${image}`], { capture: false });
      return { builderImage: image };
    }
    const repo = resolveRepo(cfg);
    const tag = gitShortSha();
    const gatewayImage = `${repo}/${cfg.gatewayService}:${tag}`;
    const workerImage = `${repo}/${cfg.workerService}:${tag}`;
    log(`building gateway → ${gatewayImage}`);
    run("gcloud", ["builds", "submit", ".", "--project", cfg.project, "--tag", gatewayImage], { capture: false });
    log(`building worker → ${workerImage}`);
    run("gcloud", ["builds", "submit", "apps/ge-demo-generator", "--project", cfg.project, "--tag", workerImage], { capture: false });
    return { gatewayImage, workerImage };
  }

  function deploy(cfg, { target = "all", log = noop } = {}) {
    // Gate: builds images and runs terraform apply against real Cloud Run.
    const { dryRun } = authorize("ge factory deploy", { mode: cfg.mode });
    ensureGcloud();
    ensureTerraform();
    if (!cfg.project) throw new Error("No project. Run `ge init`.");
    if (dryRun) {
      log("[dry-run] skipping image build + terraform apply — set GE_CONFIRM=1 to deploy");
      return { deployed: [], dryRun: true };
    }
    log("building gateway + worker images");
    const { gatewayImage, workerImage } = build(cfg, { log });
    log("binding images via terraform apply (Terraform owns Cloud Run config)");
    infra(cfg, { sub: "apply", gatewayImage, workerImage, log });
    const deployed = target === "gateway" ? [cfg.gatewayService]
      : target === "worker" ? [cfg.workerService]
      : [cfg.gatewayService, cfg.workerService];
    return { deployed, gatewayImage, workerImage };
  }

  function doctor(cfg) {
    ensureGcloud();
    if (!cfg.project) throw new Error("No project. Run `ge init` first.");
    const collector = createCheckCollector();
    const { add } = collector;

    const auth = gcloud(["auth", "list", "--filter=status:ACTIVE", "--format=value(account)"], { allowFail: true });
    add("gcloud auth", auth.ok && auth.out ? "pass" : "fail", auth.out || "no active account", "gcloud auth login");

    for (const [label, svc] of [["gateway", cfg.gatewayService], ["worker", cfg.workerService]]) {
      const service = describeRun(cfg, svc);
      if (!service) {
        add(`${label} service`, "fail", `${svc} not found`, `ge deploy ${label}`);
        continue;
      }
      const ready = (service.status?.conditions || []).find((condition) => condition.type === "Ready");
      add(`${label} ready`, ready?.status === "True" ? "pass" : "fail", `${svc}: ${ready?.status || "?"} ${ready?.message || ""}`, `ge logs --service ${svc}`);
      if (serviceIapEnabled(service)) add(`${label} IAP`, "warn", "platform IAP enabled — blocks programmatic calls", `gcloud run services update ${svc} --project ${cfg.project} --region ${cfg.region} --no-iap`);
      const memory = serviceMemory(service);
      if (label === "gateway" && memory && /^(128|256|384)Mi$/.test(memory)) add("gateway memory", "fail", `${memory} — too small, OOMs during scaffolding`, "ge deploy gateway");
      if (label === "gateway") {
        const workerUrl = serviceEnv(service, "GE_AGENT_FACTORY_WORKER_URL");
        add("gateway GE_AGENT_FACTORY_WORKER_URL", workerUrl ? "pass" : "fail", workerUrl || "empty (gateway crashes on boot)", "ge deploy gateway");
      }
    }

    const policy = gcloud(["run", "services", "get-iam-policy", cfg.workerService, "--project", cfg.project, "--region", cfg.region, "--format=json"], { allowFail: true });
    const invoker = policy.ok && parseBindings(policy.out).some((binding) => binding.role === "roles/run.invoker" && (binding.members || []).some((member) => member.includes(cfg.serviceAccount)));
    add("runner SA → worker invoker", invoker ? "pass" : "warn", invoker ? cfg.serviceAccount : `not granted to ${cfg.serviceAccount}`,
      `gcloud run services add-iam-policy-binding ${cfg.workerService} --project ${cfg.project} --region ${cfg.region} --member=serviceAccount:${cfg.serviceAccount} --role=roles/run.invoker`);

    const queue = gcloud(["tasks", "queues", "describe", cfg.tasksQueue, "--location", cfg.region, "--project", cfg.project, "--format=value(state)"], { allowFail: true });
    add("tasks queue", queue.ok && queue.out === "RUNNING" ? "pass" : "warn", queue.ok ? queue.out : "not found", `gcloud tasks queues resume ${cfg.tasksQueue} --location ${cfg.region} --project ${cfg.project}`);

    return collector.report({ project: cfg.project, region: cfg.region });
  }

  return { build, builderImageTag, deploy, describeRun, doctor, infra, resolveRepo };
}
