// Lazy loader for the generated use-case catalog.
//
// The catalog (~363 entries / ~12 MB) used to be a committed `use-cases.generated.js`
// module imported at the top of server.js/factory.js — so every process paid a 12 MB
// V8 parse on cold start, and the blob dominated diffs, grep, and clone size. The
// data now lives in a git-ignored build artifact regenerated by
// `npm run use-cases:sync` (or `mise run catalog`), and this small tracked module reads
// it lazily and caches it, so commands that never touch use-cases pay nothing.
//
// Auto-sync: rather than throw when the artifact is missing or older than its
// sources, this regenerates it on first use (once per process, on the cold path).
// That kills the recurring "run mise run catalog first" footgun — a stale or absent
// catalog can no longer silently break commands or make the status board lie.
// Disable with GE_NO_CATALOG_AUTOSYNC=1 (then a missing artifact throws as before).
import { existsSync, readFileSync, statSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { globSync } from "tinyglobby";

const HERE = dirname(fileURLToPath(import.meta.url));
const APP_ROOT = join(HERE, "..");
const DATA_PATH = join(APP_ROOT, "generated", "use-cases.generated.json");
const SYNC_SCRIPT = join(APP_ROOT, "scripts", "sync-use-cases-from-okf.mjs");
// Primary source the sync reads: the committed OKF corpus (repo-root okf/,
// one Knowledge Bundle per use case). Newer source = stale artifact. Staleness
// watches each bundle's spec.json (the byte-authoritative record) plus the
// corpus root index — not the 20k concept markdown files, which the sync
// verifies against spec.json anyway. The legacy slide sources are only read by
// scripts/sync-use-cases-from-slides.mjs (bun run catalog:from-slides).
const CORPUS_SOURCE = join(APP_ROOT, "..", "..", "okf");

let cache = null;

function autosyncDisabled() {
  return ["1", "true", "yes", "on"].includes(String(process.env.GE_NO_CATALOG_AUTOSYNC || "").toLowerCase());
}

function newestMtimeMs(path, pattern = "**/*") {
  try {
    let max = statSync(path).mtimeMs;
    // Recurse via tinyglobby and take the newest mtime. The corpus pattern
    // stats one spec.json per bundle plus index.md — not the ~20k concept
    // markdown files (the sync itself verifies those against spec.json).
    for (const entry of globSync(pattern, { cwd: path, absolute: true, dot: true, onlyFiles: false })) {
      const m = statSync(entry).mtimeMs;
      if (m > max) max = m;
    }
    return max;
  } catch {
    return 0;
  }
}

function isStale() {
  if (!existsSync(DATA_PATH)) return true;
  const artifactMtime = statSync(DATA_PATH).mtimeMs;
  let scriptMtime = 0;
  try { scriptMtime = statSync(SYNC_SCRIPT).mtimeMs; } catch { /* ignore */ }
  const sourceMtime = Math.max(newestMtimeMs(CORPUS_SOURCE, "{*/spec.json,index.md}"), scriptMtime);
  return sourceMtime > artifactMtime;
}

function regenerate() {
  process.stderr.write(`[use-cases] catalog missing or stale — regenerating ${relative(APP_ROOT, DATA_PATH)} (set GE_NO_CATALOG_AUTOSYNC=1 to disable)\n`);
  try {
    execFileSync(process.execPath, [SYNC_SCRIPT], { cwd: APP_ROOT, stdio: ["ignore", "inherit", "inherit"], timeout: 180000 });
  } catch (error) {
    throw new Error(`Use-case catalog auto-sync failed (${SYNC_SCRIPT}): ${error.message}. Run \`mise run catalog\` manually or set GE_NO_CATALOG_AUTOSYNC=1.`);
  }
}

export function getUseCases() {
  if (cache) return cache;
  if (isStale()) {
    if (autosyncDisabled()) {
      if (!existsSync(DATA_PATH)) {
        throw new Error(
          `Use-case catalog not found at ${DATA_PATH}. It is a generated build artifact — ` +
            `run \`npm run use-cases:sync\` (or \`mise run catalog\`), or unset GE_NO_CATALOG_AUTOSYNC to auto-generate.`,
        );
      }
    } else {
      regenerate();
    }
  }
  if (!existsSync(DATA_PATH)) {
    throw new Error(`Use-case catalog still missing at ${DATA_PATH} after auto-sync. Run \`mise run catalog\` and check its output.`);
  }
  cache = JSON.parse(readFileSync(DATA_PATH, "utf8"));
  return cache;
}
