// okf-corpus.mjs — the committed OKF corpus (repo-root `okf/`) as a library.
//
// The corpus is the PRIMARY source of the agent catalog: one Knowledge Bundle
// per use case at `okf/<use-case-id>/`, plus a generated corpus root index at
// `okf/index.md`. Each bundle carries:
//
//   - `index.md` — bundle root: `okf_version: "0.1"` frontmatter with
//     provenance keys (`provenance_origin` deck|interview, `provenance_status`
//     registered, `provenance_version`, `provenance_created_at` — pinned to
//     MIGRATION_TIMESTAMP, never wall clock), then the concept tree that
//     `spec-to-okf.mjs` emits (playbook, systems/, tables/, tools/, ...).
//   - `spec.json` — the full normalized catalog entry (the byte-authoritative
//     field record this wave; `sync-use-cases-from-okf.mjs` assembles the
//     generated catalog artifacts from it). The markdown concept tree is its
//     OKF projection and is kept in byte-lockstep: `verifyBundleAgainstSpec`
//     fails when the two disagree, and `migrate-catalog-to-okf.mjs --id <id>`
//     re-renders the projection after a spec.json edit.
//
// Everything here is pure or IO-returning (house rule: return/throw — the CLI
// boundaries in migrate-catalog-to-okf.mjs / sync-use-cases-from-okf.mjs render).
// Determinism contract: every byte written to the corpus is a pure function of
// (spec.json, MIGRATION_TIMESTAMP) — regeneration over unchanged inputs is a
// byte no-op, which is what makes the corpus commit-safe and drift-guardable.

import { readdir, readFile } from "node:fs/promises";
import { join, resolve } from "node:path";

import { renderConcept } from "@ge/okf";
import { compileConcepts, compileOkfBundle, rootExtensionFrontmatter } from "@ge/okf/compile";

import { buildBundle } from "../spec-to-okf.mjs";

// One fixed migration timestamp for every provenance/concept `timestamp` in the
// corpus (GE_SOURCE_DATE-style injectable clock, but with its own variable so
// ambient test pins never rewrite committed bytes; NEVER wall clock).
export const MIGRATION_TIMESTAMP = process.env.GE_OKF_MIGRATION_DATE || "2026-07-01T00:00:00.000Z";

/** Repo-root corpus directory for a given repo root. */
export function corpusRoot(repoRoot) {
  return resolve(repoRoot, "okf");
}

/** Provenance record for a catalog entry (deck for slides, interview for interviews). */
export function provenanceForEntry(entry, timestamp = MIGRATION_TIMESTAMP) {
  return {
    origin: entry.registry?.sourceKind === "interview" ? "interview" : "deck",
    sourceRef: entry.sourcePath || undefined,
    version: 1,
    status: "registered",
    createdAt: timestamp,
  };
}

/**
 * Build the in-memory concept entries (`{ relPath, frontmatter, body }`) for a
 * catalog entry: the spec-to-okf concept tree with the provenance keys merged
 * into the root index.md frontmatter. Pure given (entry, timestamp).
 */
export function bundleEntriesForSpec(entry, { timestamp = MIGRATION_TIMESTAMP } = {}) {
  const provenanceFields = rootExtensionFrontmatter({ provenance: provenanceForEntry(entry, timestamp) });
  return buildBundle(entry, { timestamp }).map((concept) => ({
    relPath: concept.relPath,
    frontmatter: concept.relPath === "index" ? { ...concept.fields, ...provenanceFields } : concept.fields,
    body: concept.body,
  }));
}

/**
 * Render a catalog entry to its full bundle file map:
 * `<relPath>.md` → concept markdown, plus `spec.json` → the normalized entry.
 */
export function bundleFilesForSpec(entry, { timestamp = MIGRATION_TIMESTAMP } = {}) {
  const files = new Map();
  for (const concept of bundleEntriesForSpec(entry, { timestamp })) {
    files.set(`${concept.relPath}.md`, renderConcept(concept.frontmatter, concept.body));
  }
  files.set("spec.json", `${JSON.stringify(entry, null, 2)}\n`);
  return files;
}

/** The corpus root `okf/index.md` — all bundles, deterministically ordered by id. */
export function corpusIndexContent(entries, { timestamp = MIGRATION_TIMESTAMP } = {}) {
  const sorted = [...entries].sort((a, b) => String(a.id).localeCompare(String(b.id)));
  const body = [
    "# OKF Corpus",
    "",
    "The committed source of the agent catalog: one Knowledge Bundle per use",
    "case. Generated by `apps/factory/scripts/migrate-catalog-to-okf.mjs` and",
    "kept fresh by `bun run catalog` — do not edit by hand.",
    "",
    "## Bundles",
    "",
    sorted.map((entry) => `- [${entry.title}](/${entry.id}/index.md)`).join("\n"),
  ].join("\n");
  return renderConcept(
    {
      type: "Index",
      title: "GE Agent Factory — OKF Corpus",
      description: `Corpus root index: ${sorted.length} Knowledge Bundles, one per catalog use case.`,
      timestamp,
    },
    body,
  );
}

/** List the corpus bundle directory names (sorted; ignores plain files like index.md). */
export async function listBundleDirs(root) {
  const dirents = await readdir(root, { withFileTypes: true }).catch((error) => {
    if (error.code === "ENOENT") return [];
    throw error;
  });
  return dirents
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
}

async function walkMarkdown(dir, prefix = "") {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) out.push(...(await walkMarkdown(join(dir, entry.name), rel)));
    else if (entry.name.endsWith(".md")) out.push(rel);
  }
  return out;
}

/** Read a bundle's spec.json (throws with a fix hint when absent/invalid). */
export async function readBundleSpec(bundleDir) {
  const path = join(bundleDir, "spec.json");
  let raw;
  try {
    raw = await readFile(path, "utf8");
  } catch {
    throw new Error(`${path} is missing — every okf/ bundle carries its normalized spec record; regenerate it with: bun run catalog:migrate`);
  }
  try {
    return JSON.parse(raw);
  } catch (error) {
    throw new Error(`${path} is not valid JSON (${error.message}) — regenerate it with: bun run catalog:migrate`);
  }
}

const sortedJson = (value) => JSON.stringify(value);

/**
 * Verify one on-disk bundle against its source spec. Returns a structured
 * `{ ok, problems }` report (never throws on content problems):
 *
 *   1. LOCKSTEP — the on-disk concept tree byte-matches a fresh in-memory
 *      rebuild from the spec (missing/extra/drifted .md files are named).
 *   2. COMPILE — `compileOkfBundle` on the on-disk bundle reports zero errors.
 *   3. PARITY — the compiled spec JSON of the on-disk bundle byte-matches the
 *      compiled spec JSON of the in-memory rebuild (the wave-A harness
 *      pattern: compile(spec→okf(spec)) is byte-stable end to end).
 *   4. INVARIANTS — tool names, source-system / entity / workflow-step counts
 *      recovered by the compiler match the source spec.
 */
export async function verifyBundleAgainstSpec(bundleDir, entry, { timestamp = MIGRATION_TIMESTAMP } = {}) {
  const problems = [];
  const expected = bundleFilesForSpec(entry, { timestamp });

  // 1. lockstep: byte-compare every expected file; flag extras.
  const diskMarkdown = new Set(await walkMarkdown(bundleDir));
  for (const [rel, content] of expected) {
    if (rel === "spec.json") continue; // the spec record is the rebuild input, not an output to compare
    if (!diskMarkdown.has(rel)) {
      problems.push({ kind: "missing-file", file: rel, fix: "bun run catalog:migrate" });
      continue;
    }
    const disk = await readFile(join(bundleDir, rel), "utf8");
    if (disk !== content) {
      problems.push({
        kind: "content-drift",
        file: rel,
        fix: `edit spec.json and re-render with \`node apps/factory/scripts/migrate-catalog-to-okf.mjs --id ${entry.id}\` (concept markdown is the generated OKF projection of spec.json this wave)`,
      });
    }
  }
  for (const rel of diskMarkdown) {
    if (!expected.has(rel)) problems.push({ kind: "extra-file", file: rel, fix: "delete it or regenerate the bundle with: bun run catalog:migrate" });
  }

  // 2 + 3. compile the on-disk bundle and the in-memory rebuild; both must be
  // error-free and emit byte-identical spec JSON.
  const disk = await compileOkfBundle(bundleDir);
  for (const error of disk.errors) {
    problems.push({ kind: "compile-error", code: error.code, conceptPath: error.conceptPath, message: error.message, fix: error.fix });
  }
  const memory = await compileConcepts(bundleEntriesForSpec(entry, { timestamp }));
  for (const error of memory.errors) {
    problems.push({ kind: "compile-error", code: error.code, conceptPath: `(rebuild) ${error.conceptPath}`, message: error.message, fix: error.fix });
  }
  if (sortedJson(disk.spec) !== sortedJson(memory.spec)) {
    problems.push({
      kind: "compile-parity",
      message: "compileOkfBundle(on-disk bundle) and compile(rebuilt-from-spec bundle) emit different spec JSON",
      fix: "bun run catalog:migrate",
    });
  }

  // 4. invariants the compiler must recover from the source spec.
  const bc = entry.generationSpec?.behaviorContract || {};
  const srcTools = (bc.toolIntents || []).map((tool) => tool.name).sort();
  const outTools = (disk.spec.behaviorContract?.toolIntents || []).map((tool) => tool.name).sort();
  if (sortedJson(srcTools) !== sortedJson(outTools)) {
    problems.push({ kind: "invariant", message: `recovered tool names ${sortedJson(outTools)} != source ${sortedJson(srcTools)}` });
  }
  const counts = [
    ["sourceSystems", (entry.generationSpec?.sourceSystems || []).length, (disk.spec.generationSpec?.sourceSystems || []).length],
    ["entities", (entry.generationSpec?.entities || []).length, (disk.spec.generationSpec?.entities || []).length],
    ["workflow steps", bc.workflow?.steps?.length || 0, disk.spec.behaviorContract?.workflow?.steps?.length || 0],
  ];
  for (const [what, src, out] of counts) {
    if (src !== out) problems.push({ kind: "invariant", message: `recovered ${what} count ${out} != source ${src}` });
  }

  return { ok: problems.length === 0, problems };
}
