// k6 export — emit a standalone load script for teams whose load tooling is
// already k6. Deliberately minimal in v1: auth is an access token in an env
// var (documented in the script header), not a reimplementation of ADC.
export function renderK6Script({ target, sessions = 5, turnsPerSession = 2, turnTexts = ["Hello"], budgets = {} }) {
  const header = `// k6 load script generated by \`ge bench --export k6\`.
//
// Auth: export GOOGLE_OAUTH_ACCESS_TOKEN before running, e.g.
//   export GOOGLE_OAUTH_ACCESS_TOKEN=$(gcloud auth print-access-token)
//   k6 run bench.k6.js
//
// The script drives the same streaming assist endpoint \`ge drive\` uses and
// threads the returned session across turns. Streaming granularity (time to
// first chunk) is not observable from k6's http client — use \`ge bench\` for
// ttft/stall budgets; use this for volume.`;
  return `${header}
import http from "k6/http";
import { check, sleep } from "k6";

const URL = ${JSON.stringify(target.url)};
const TURNS = ${JSON.stringify(turnTexts, null, 2)};

export const options = {
  vus: ${Math.min(sessions, 10)},
  iterations: ${sessions},
  thresholds: {
    http_req_duration: ["p(95)<${budgets.fullResponseMsP95 ?? 15000}"],
    http_req_failed: ["rate<${budgets.errorRateMax ?? 0.01}"],
  },
};

export default function () {
  let session = null;
  for (let turn = 0; turn < ${turnsPerSession}; turn += 1) {
    const body = { query: { text: TURNS[turn % TURNS.length] } };
    if (session) body.session = session;
    const res = http.post(URL, JSON.stringify(body), {
      headers: {
        "content-type": "application/json",
        authorization: \`Bearer \${__ENV.GOOGLE_OAUTH_ACCESS_TOKEN}\`,
      },
    });
    check(res, { "status 200": (r) => r.status === 200 });
    try {
      const chunks = JSON.parse(res.body);
      for (const chunk of chunks) if (chunk.sessionInfo && chunk.sessionInfo.session) session = chunk.sessionInfo.session;
    } catch (e) { /* non-JSON error body: the status check above already failed the iteration */ }
    sleep(0.5);
  }
}
`;
}
