// tools/ge/completions.mjs — `ge completions bash|zsh|fish`.
//
// Walks the same citty command tree tools/gen-cli-reference.mjs renders docs
// from (tools/ge.mjs's `rootCommand`) to emit a shell completion script that
// offers subcommand names at each level (`ge <TAB>` -> agents/mcp/data/...,
// `ge agents <TAB>` -> build/register/track/...). Flag completion is out of
// scope for this first pass — completing the noun/verb tree is the everyday
// win; every command's flags are already discoverable via `--help`.
//
// Dynamically imports ../ge.mjs (rather than a static import) because this
// module IS one of ge.mjs's own subcommands — a static import would be a
// cycle. By the time `ge completions <shell>` actually runs, ge.mjs has
// already finished loading, so the dynamic import just returns the cached
// module.
import { defineCommand } from "citty";

// citty allows lazy subcommands (`() => import(...)`); resolve either shape.
// Unwrap `.default` ONLY for module-namespace wrappers: a command object may
// itself carry citty's default-SUBCOMMAND key (a string naming the subcommand
// a bare invocation dispatches to — see tools/ge/handoff.mjs), which must not
// be mistaken for the command.
async function resolveCommand(cmd) {
  const resolved = typeof cmd === "function" ? await cmd() : await cmd;
  if (resolved && typeof resolved === "object" && (resolved.meta || resolved.args || resolved.run || resolved.subCommands)) {
    return resolved;
  }
  return resolved?.default ?? resolved;
}

// Build { name, subcommands: { name: node, ... } } recursively. Leaf commands
// have an empty subcommands object.
export async function buildTree(cmd, name) {
  cmd = await resolveCommand(cmd);
  const subEntries = Object.entries(cmd.subCommands ?? {});
  const subcommands = {};
  for (const [subName, sub] of subEntries) {
    subcommands[subName] = await buildTree(sub, subName);
  }
  return { name, subcommands };
}

export function renderBash(tree) {
  // One case arm per group that has subcommands; the top-level offers every
  // group name. COMP_WORDS[1] is the group (if any); deeper nesting doesn't
  // exist in this tree today, but the case statement falls through safely
  // (no completions) if it ever does.
  const groups = Object.values(tree.subcommands).filter((n) => Object.keys(n.subcommands).length > 0);
  const topWords = Object.keys(tree.subcommands).join(" ");
  const cases = groups
    .map((g) => `    ${g.name}) COMPREPLY=($(compgen -W "${Object.keys(g.subcommands).join(" ")}" -- "$cur")) ;;`)
    .join("\n");
  return `# ge bash completion — generated by \`ge completions bash\`; source it, e.g.:
#   ge completions bash > ~/.local/share/bash-completion/completions/ge
_ge_completions() {
  local cur prev
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[1]}"
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=($(compgen -W "${topWords}" -- "$cur"))
    return
  fi
  case "$prev" in
${cases}
    *) COMPREPLY=() ;;
  esac
}
complete -F _ge_completions ge
`;
}

export function renderZsh(tree) {
  const groups = Object.values(tree.subcommands).filter((n) => Object.keys(n.subcommands).length > 0);
  const topWords = Object.keys(tree.subcommands).map((n) => `'${n}'`).join(" ");
  const cases = groups
    .map((g) => `    ${g.name}) _values '${g.name} subcommand' ${Object.keys(g.subcommands).map((n) => `'${n}'`).join(" ")} ;;`)
    .join("\n");
  return `#compdef ge
# ge zsh completion — generated by \`ge completions zsh\`; source it, e.g.:
#   ge completions zsh > ~/.zsh/completions/_ge   (then make sure that dir is on fpath)
_ge() {
  local -a top
  top=(${topWords})
  if (( CURRENT == 2 )); then
    _values 'ge command' \${top[@]}
    return
  fi
  case "\${words[2]}" in
${cases}
    *) ;;
  esac
}
_ge
`;
}

export function renderFish(tree) {
  const lines = [
    "# ge fish completion — generated by `ge completions fish`; source it, e.g.:",
    "#   ge completions fish > ~/.config/fish/completions/ge.fish",
  ];
  for (const name of Object.keys(tree.subcommands)) {
    lines.push(`complete -c ge -n "__fish_use_subcommand" -f -a "${name}"`);
  }
  for (const group of Object.values(tree.subcommands)) {
    const subNames = Object.keys(group.subcommands);
    if (!subNames.length) continue;
    for (const sub of subNames) {
      lines.push(`complete -c ge -n "__fish_seen_subcommand_from ${group.name}" -f -a "${sub}"`);
    }
  }
  return lines.join("\n") + "\n";
}

const RENDERERS = { bash: renderBash, zsh: renderZsh, fish: renderFish };

export const completions = defineCommand({
  meta: { name: "completions", description: "Emit a shell completion script for `ge` (bash|zsh|fish) — subcommand names only, not flags" },
  args: {
    shell: { type: "positional", required: true, description: "bash, zsh, or fish" },
  },
  async run({ args }) {
    const renderer = RENDERERS[args.shell];
    if (!renderer) {
      process.stderr.write(`✗ unknown shell "${args.shell}" — expected one of: ${Object.keys(RENDERERS).join(", ")}\n`);
      process.exitCode = 1;
      return;
    }
    const { rootCommand } = await import("../ge.mjs");
    const tree = await buildTree(rootCommand, "ge");
    process.stdout.write(renderer(tree));
  },
});
