import { defineCommand } from "citty";
import pc from "picocolors";
import { common, emit, guarded, out, ui } from "./shared.mjs";
import { generateLibraryIndex, readLibraryIndex, searchBlueprints, resolveBlueprint, blueprintStatus, relatedBlueprints } from "../lib/agent-library.mjs";

function renderStats(r){ out(ui.title("Agent Library")); out(ui.kv([["blueprints", String(r.counts.blueprints)], ["verticals", String(r.counts.verticals)], ["buildable", String(r.counts.buildable)], ["proven", String(r.counts.proven)]])); }
function renderRows(rows){ for (const b of rows) out(`${pc.bold(b.title)}\n  ${pc.cyan(b.slug)}\n  ${[b.taxonomy.vertical,b.taxonomy.domain].filter(Boolean).join(" · ")}\n  ${b.inventory.sourceSystems} systems · ${b.inventory.toolIntents} tools · ${b.inventory.evals} evals · ${b.behavior.humanApprovalPoints} approval gates\n  Status: ${b.status}\n  Create: ${pc.cyan(b.commands.create)}\n`); }
function renderInspect(b){ out(ui.title(b.title, b.slug)); out(ui.kv([["status", b.status], ["version", b.version], ["OKF", b.okf.bundlePath], ["source", b.okf.sourceSpecPath || "unknown"], ["authority", b.behavior.authorityLevel], ["trigger", b.behavior.trigger], ["systems", String(b.inventory.sourceSystems)], ["tools", String(b.inventory.toolIntents)], ["evals", String(b.inventory.evals)]])); out("\nCommands"); out(`  ${pc.cyan(b.commands.inspect)}`); out(`  ${pc.cyan(b.commands.create)}`); out(`  ${pc.cyan(b.commands.prove)}`); }
const stats=defineCommand({ meta:{name:"stats",description:"Show Agent Library inventory counts"}, args:{...common}, run: guarded(async({args})=>emit(args, await readLibraryIndex(), renderStats)) });
const list=defineCommand({ meta:{name:"list",description:"List Agent Library blueprints"}, args:{...common, limit:{type:"string",default:"25"}}, run: guarded(async({args})=>{const idx=await readLibraryIndex(); const rows=idx.blueprints.slice(0, Number(args.limit)); emit(args,{...idx,blueprints:rows}, r=>renderRows(r.blueprints));}) });
const search=defineCommand({ meta:{name:"search",description:"Search Agent Library blueprints"}, args:{...common, query:{type:"positional",required:false}, vertical:{type:"string"}, department:{type:"string"}, domain:{type:"string"}, system:{type:"string"}, target:{type:"string"}, status:{type:"string"}, authority:{type:"string"}}, run: guarded(async({args})=>{ const rows=await searchBlueprints(args.query||"", args); emit(args,{ok:true, query:args.query||"", count:rows.length, blueprints:rows}, r=>renderRows(r.blueprints)); }) });
const inspect=defineCommand({ meta:{name:"inspect",description:"Inspect a blueprint package"}, args:{...common, slug:{type:"positional",required:true}}, run: guarded(async({args})=>emit(args, await resolveBlueprint(args.slug), renderInspect)) });
const explain=defineCommand({ meta:{name:"explain",description:"Explain a blueprint's behavior contract and next steps"}, args:{...common, slug:{type:"positional",required:true}}, run: guarded(async({args})=>emit(args, await resolveBlueprint(args.slug), b=>{ renderInspect(b); out("\nObjective"); out(`  ${b.behavior.objective}`); out(ui.next(b.commands.create)); })) });
const status=defineCommand({ meta:{name:"status",description:"Show computed blueprint lifecycle readiness"}, args:{...common, slug:{type:"positional",required:true}}, run: guarded(async({args})=>emit(args, await blueprintStatus(args.slug), r=>{ out(ui.title(r.id)); out(ui.kv([["state", r.state], ["blockers", r.blockers.length ? r.blockers.join(", ") : "none"]])); out(ui.next(r.nextCommand)); })) });
const related=defineCommand({ meta:{name:"related",description:"Show related blueprints"}, args:{...common, slug:{type:"positional",required:true}}, run: guarded(async({args})=>emit(args, { blueprints: await relatedBlueprints(args.slug) }, r=>renderRows(r.blueprints))) });
const doctor=defineCommand({ meta:{name:"doctor",description:"Check the generated Agent Library index"}, args:{...common}, run: guarded(async({args})=>{ const idx=await readLibraryIndex(); emit(args,{ok:true, checks:[{name:"index",status:"pass"}], counts:idx.counts}, r=>{ out(ui.title("Agent Library Doctor")); out(`  ${pc.green("✓")} index readable (${r.counts.blueprints} blueprints)`); }); }) });
const refreshIndex=defineCommand({ meta:{name:"refresh-index",description:"Regenerate okf/library/index.json from OKF bundles"}, args:{...common}, run: guarded(async({args})=>emit(args, await generateLibraryIndex(), r=>{ renderStats(r); out(pc.dim("  wrote okf/library/index.json")); })) });
export const library = defineCommand({ meta:{name:"library",description:"Agent Library package manager: stats · list · search · inspect · create"}, subCommands:{stats,list,search,inspect,explain,status,related,doctor,"refresh-index":refreshIndex} });
