// Lazy loader for the generated use-case catalog.
//
// The catalog (~363 entries / ~12 MB) used to be a committed `use-cases.generated.js`
// module imported at the top of server.js/factory.js — so every process paid a 12 MB
// V8 parse on cold start, and the blob dominated diffs, grep, and clone size. The
// data now lives in a git-ignored build artifact regenerated by
// `npm run use-cases:sync` (or `make catalog`), and this small tracked module reads
// it lazily and caches it, so commands that never touch use-cases pay nothing.
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const DATA_PATH = join(dirname(fileURLToPath(import.meta.url)), "..", "generated", "use-cases.generated.json");

let cache = null;

export function getUseCases() {
  if (cache) return cache;
  if (!existsSync(DATA_PATH)) {
    throw new Error(
      `Use-case catalog not found at ${DATA_PATH}. It is a generated build artifact — ` +
        `run \`npm run use-cases:sync\` (or \`make catalog\`) to produce it.`,
    );
  }
  cache = JSON.parse(readFileSync(DATA_PATH, "utf8"));
  return cache;
}
