#!/usr/bin/env bash
# Writes apps/presentation/.env.local from Terraform outputs so a local
# `bun run dev` session points at the same project, bucket, SAs, and GE app
# the deployed gateway was provisioned with.
#
# Run from the installer/ directory after `terraform apply` succeeds:
#   ./scripts/generate-env.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALLER_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${INSTALLER_DIR}/.." && pwd)"
TF_DIR="${INSTALLER_DIR}/terraform"
ENV_FILE="${REPO_ROOT}/apps/presentation/.env.local"

if ! command -v terraform >/dev/null 2>&1; then
  echo "terraform not found on PATH" >&2
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "jq not found on PATH" >&2
  exit 1
fi

cd "${TF_DIR}"
OUTPUTS_JSON="$(terraform output -json)"

get() {
  printf '%s' "${OUTPUTS_JSON}" | jq -r ".${1}.value // empty"
}

PROJECT_ID="$(get project_id)"
PROJECT_NUMBER="$(get project_number)"
REGION="$(get region)"
GATEWAY_URL="$(get gateway_url)"
WORKER_URL="$(get worker_url)"
FACTORY_BUCKET="$(get factory_bucket)"
RUNNER_SA="$(get runner_service_account)"
TASKS_QUEUE="$(get tasks_queue)"
GE_APP_ID="$(get gemini_enterprise_app_id)"
GE_LOCATION="$(get gemini_enterprise_location)"

if [[ -z "${PROJECT_ID}" ]]; then
  echo "Terraform outputs are empty — did you run 'terraform apply'?" >&2
  exit 1
fi

mkdir -p "$(dirname "${ENV_FILE}")"

cat > "${ENV_FILE}" <<EOF
# Generated by installer/scripts/generate-env.sh — re-run after terraform apply.
# Safe to commit-ignore; values reflect your provisioned project.

# Vite (consumed at build time by the React app)
VITE_DEFAULT_PROJECT_ID=${PROJECT_ID}
VITE_GATEWAY_URL=${GATEWAY_URL}

# Presentation server (apps/presentation/server.js)
PORT=5173
GOOGLE_CLOUD_PROJECT=${PROJECT_ID}
GOOGLE_CLOUD_LOCATION=${GE_LOCATION}
GOOGLE_GENAI_USE_VERTEXAI=TRUE
GE_AGENT_FACTORY_BUCKET=${FACTORY_BUCKET}
GE_AGENT_FACTORY_QUEUE=${TASKS_QUEUE}
GE_AGENT_FACTORY_REGION=${REGION}
GE_AGENT_FACTORY_SERVICE_ACCOUNT=${RUNNER_SA}
GE_AGENT_FACTORY_WORKER_URL=${WORKER_URL}
GEMINI_ENTERPRISE_APP_ID=${GE_APP_ID}
GEMINI_ENTERPRISE_LOCATION=${GE_LOCATION}
GOOGLE_CLOUD_PROJECT_NUMBER=${PROJECT_NUMBER}

# Local dev defaults: IAP off, no OIDC allowlist. The deployed gateway uses
# whatever you set in values.tfvars.
REQUIRE_IAP=false
EOF

echo "Wrote ${ENV_FILE}"
