import {
  BarChart3,
  UserPlus,
  Trophy,
  Scale,
  GraduationCap,
  ShieldCheck,
  Heart,
  Settings,
  Users,
  LineChart,
  Target,
  Layers,
  Search,
  FileSignature,
  CreditCard,
  AlertTriangle,
  Star,
  ShoppingCart,
  TrendingUp,
  // Finance icons
  Calculator,
  BookOpen,
  Receipt,
  Banknote,
  Landmark,
  Building2,
  ClipboardCheck,
  PiggyBank,
  FileSpreadsheet,
  // IT icons
  Monitor,
  Code,
  Cloud,
  Shield,
  Headphones,
  Database,
  Network,
  FileCheck,
  Laptop,
  // Marketing icons
  Megaphone,
  Palette,
  Crosshair,
  Globe,
  MessageCircle,
  PieChart,
  Award,
  Wrench,
  Radar
} from "lucide-react";
import { DOMAIN_COLORS } from "../design-tokens";

export const DOMAINS = [
  // HR Domains (1-10)
  { id: "domain-1", title: "Workforce Planning", icon: BarChart3, color: DOMAIN_COLORS[1] },
  { id: "domain-2", title: "Talent Acquisition", icon: UserPlus, color: DOMAIN_COLORS[2] },
  { id: "domain-3", title: "Performance Mgmt", icon: Trophy, color: DOMAIN_COLORS[3] },
  { id: "domain-4", title: "Total Rewards", icon: Scale, color: DOMAIN_COLORS[4] },
  { id: "domain-5", title: "Learning & Dev", icon: GraduationCap, color: DOMAIN_COLORS[5] },
  { id: "domain-6", title: "ER & Compliance", icon: ShieldCheck, color: DOMAIN_COLORS[6] },
  { id: "domain-7", title: "Engagement", icon: Heart, color: DOMAIN_COLORS[7] },
  { id: "domain-8", title: "HR Operations", icon: Settings, color: DOMAIN_COLORS[8] },
  { id: "domain-9", title: "DEI & Belonging", icon: Users, color: DOMAIN_COLORS[9] },
  { id: "domain-10", title: "People Analytics", icon: LineChart, color: DOMAIN_COLORS[10] },
  // Procurement Domains (11-19)
  { id: "domain-11", title: "Procurement Strategy", icon: Target, color: DOMAIN_COLORS[11] },
  { id: "domain-12", title: "Strategic Sourcing", icon: Layers, color: DOMAIN_COLORS[12] },
  { id: "domain-13", title: "Supplier Discovery", icon: Search, color: DOMAIN_COLORS[13] },
  { id: "domain-14", title: "Contract Lifecycle", icon: FileSignature, color: DOMAIN_COLORS[14] },
  { id: "domain-15", title: "Procure-to-Pay", icon: CreditCard, color: DOMAIN_COLORS[15] },
  { id: "domain-16", title: "Supplier Risk", icon: AlertTriangle, color: DOMAIN_COLORS[16] },
  { id: "domain-17", title: "Supplier Performance", icon: Star, color: DOMAIN_COLORS[17] },
  { id: "domain-18", title: "Indirect & Tail Spend", icon: ShoppingCart, color: DOMAIN_COLORS[18] },
  { id: "domain-19", title: "Spend Analytics", icon: TrendingUp, color: DOMAIN_COLORS[19] },
  // Finance Domains (20-28)
  { id: "domain-20", title: "FP&A", icon: Calculator, color: DOMAIN_COLORS[20] },
  { id: "domain-21", title: "General Ledger & Close", icon: BookOpen, color: DOMAIN_COLORS[21] },
  { id: "domain-22", title: "Accounts Payable", icon: Receipt, color: DOMAIN_COLORS[22] },
  { id: "domain-23", title: "Accounts Receivable", icon: Banknote, color: DOMAIN_COLORS[23] },
  { id: "domain-24", title: "Treasury & Cash", icon: Landmark, color: DOMAIN_COLORS[24] },
  { id: "domain-25", title: "Tax & Compliance", icon: Building2, color: DOMAIN_COLORS[25] },
  { id: "domain-26", title: "Internal Audit", icon: ClipboardCheck, color: DOMAIN_COLORS[26] },
  { id: "domain-27", title: "Revenue & Cost Acctg", icon: PiggyBank, color: DOMAIN_COLORS[27] },
  { id: "domain-28", title: "Finance Analytics", icon: FileSpreadsheet, color: DOMAIN_COLORS[28] },
  // Marketing Domains (29-37)
  { id: "domain-29", title: "Marketing Strategy", icon: Megaphone, color: DOMAIN_COLORS[29] },
  { id: "domain-30", title: "Content & Creative", icon: Palette, color: DOMAIN_COLORS[30] },
  { id: "domain-31", title: "Demand Generation", icon: Crosshair, color: DOMAIN_COLORS[31] },
  { id: "domain-32", title: "Digital & SEO/SEM", icon: Globe, color: DOMAIN_COLORS[32] },
  { id: "domain-33", title: "Social & Community", icon: MessageCircle, color: DOMAIN_COLORS[33] },
  { id: "domain-34", title: "Marketing Analytics", icon: PieChart, color: DOMAIN_COLORS[34] },
  { id: "domain-35", title: "Brand & Comms", icon: Award, color: DOMAIN_COLORS[35] },
  { id: "domain-36", title: "Marketing Operations", icon: Wrench, color: DOMAIN_COLORS[36] },
  { id: "domain-37", title: "Customer & Market Intel", icon: Radar, color: DOMAIN_COLORS[37] },
  // IT Domains (38-46)
  { id: "domain-38", title: "IT Strategy & Portfolio", icon: Monitor, color: DOMAIN_COLORS[38] },
  { id: "domain-39", title: "Software Eng & DevOps", icon: Code, color: DOMAIN_COLORS[39] },
  { id: "domain-40", title: "Infra & Cloud Ops", icon: Cloud, color: DOMAIN_COLORS[40] },
  { id: "domain-41", title: "Cybersecurity & Threat", icon: Shield, color: DOMAIN_COLORS[41] },
  { id: "domain-42", title: "IT Service Mgmt", icon: Headphones, color: DOMAIN_COLORS[42] },
  { id: "domain-43", title: "Data & AI Platform", icon: Database, color: DOMAIN_COLORS[43] },
  { id: "domain-44", title: "Enterprise Architecture", icon: Network, color: DOMAIN_COLORS[44] },
  { id: "domain-45", title: "IT Governance", icon: FileCheck, color: DOMAIN_COLORS[45] },
  { id: "domain-46", title: "End User Computing", icon: Laptop, color: DOMAIN_COLORS[46] },
];
