import { expect, test } from "bun:test";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { GENERATED_FILES, checkGeneratedDrift, formatDriftReport } from "./check-generated-drift.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");

// A synthetic generator that writes fixed bytes to the checker's temp path
// (exposed via the row's outEnv), so drift/no-drift can be planted precisely.
function syntheticRow(tmp, { generated, tracked, exitCode = 0, id = "synthetic" }) {
  const trackedFile = "tracked.generated.txt";
  if (tracked !== undefined) writeFileSync(join(tmp, trackedFile), tracked);
  const script = exitCode === 0
    ? `require("fs").writeFileSync(process.env.SYNTH_OUT, ${JSON.stringify(generated ?? "")});`
    : `console.error("synthetic generator exploded"); process.exit(${exitCode});`;
  return {
    id,
    trackedFile,
    command: ["node", "-e", script],
    outEnv: "SYNTH_OUT",
    regenerate: "bun run synthetic:regen",
  };
}

function withTmp(fn) {
  const tmp = mkdtempSync(join(tmpdir(), "check-generated-drift-test-"));
  try {
    return fn(tmp);
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

test("identical tracked and regenerated bytes pass", () => {
  withTmp((tmp) => {
    const row = syntheticRow(tmp, { generated: "same\nbytes\n", tracked: "same\nbytes\n" });
    const result = checkGeneratedDrift([row], { root: tmp });
    expect(result.findings).toEqual([]);
    expect(result.ok).toBe(true);
    expect(formatDriftReport(result)).toContain("1 tracked generated file byte-match");
  });
});

test("planted drift fails with the first differing line and the regenerate hint", () => {
  withTmp((tmp) => {
    const row = syntheticRow(tmp, { generated: "line1\nline2-new\n", tracked: "line1\nline2-old\n" });
    const result = checkGeneratedDrift([row], { root: tmp });
    expect(result.ok).toBe(false);
    expect(result.findings.map((f) => f.file)).toEqual(["tracked.generated.txt"]);
    expect(result.findings[0].drift.line).toBe(2);
    const report = formatDriftReport(result);
    expect(report).toContain("-tracked:     line2-old");
    expect(report).toContain("+regenerated: line2-new");
    expect(report).toContain("bun run synthetic:regen");
    expect(report).toContain("byte no-op");
  });
});

test("a failing generator is reported as a failure, not silently skipped", () => {
  withTmp((tmp) => {
    const row = syntheticRow(tmp, { tracked: "whatever\n", exitCode: 3 });
    const result = checkGeneratedDrift([row], { root: tmp });
    expect(result.ok).toBe(false);
    expect(result.findings[0].generatorFailed).toBe(true);
    expect(formatDriftReport(result)).toContain("synthetic generator exploded");
  });
});

test("a missing tracked file is drift", () => {
  withTmp((tmp) => {
    const row = syntheticRow(tmp, { generated: "content\n" }); // tracked never written
    const result = checkGeneratedDrift([row], { root: tmp });
    expect(result.ok).toBe(false);
    expect(result.findings[0].missing).toBe(true);
    expect(formatDriftReport(result)).toContain("bun run synthetic:regen");
  });
});

test("declared rows carry everything the checker needs", () => {
  for (const row of GENERATED_FILES) {
    expect(typeof row.id).toBe("string");
    expect(row.trackedFile).toMatch(/\.generated\./);
    expect(Array.isArray(row.command) && row.command.length > 0).toBe(true);
    expect(typeof row.outEnv).toBe("string");
    expect(typeof row.regenerate).toBe("string");
  }
});

// The real thing, twice: the tracked agent-spec registry byte-matches a fresh
// regeneration, and regenerating AGAIN still matches — i.e. the generator is
// deterministic over unchanged inputs (taste-campaign 08 §A1's oracle: "the
// check itself, run twice in a row"). Spawns the slide sync twice (~2s each).
test("tracked generated files are byte-stable across two consecutive regenerations", () => {
  const first = checkGeneratedDrift(GENERATED_FILES, { root: ROOT });
  expect(first.findings).toEqual([]);
  expect(first.ok).toBe(true);
  const second = checkGeneratedDrift(GENERATED_FILES, { root: ROOT });
  expect(second.findings).toEqual([]);
  expect(second.ok).toBe(true);
}, 60_000);
